### ISSUE TITLE
docs/quickstart.md: Replicate an LDES with the LDES Client: doesn't connect to LDES server

### ISSUE THREAD

**Issue by ghsnd** [Informatievlaanderen/VSDS-Tech-Docs#15]
The docker compose file in [Replicate an LDES with the LDES Client](https://github.com/Informatievlaanderen/VSDS-Tech-Docs/blob/main/docs/quickstart.md#replicate-an-ldes-with-the-ldes-client) doesn't work out of the box. The issue is that it tries to connect to `localhost` from outside the `ldes` network. To fix that, the client can be told to connect to the host's network instead of the Docker network by adding `network_mode: host`:
```yaml
services:
  ldes-cli:
    image: ghcr.io/informatievlaanderen/ldes-cli:20230222T0959
    container_name: quick-start_ldes-client-cli
    command: "--url http://localhost:8080/sample/by-page --input-format text/turtle"
    network_mode: host
```
